1. Установите, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найдите размерности полученных матриц:

In [3]:
import numpy as np

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;
AB и BA - неопределены (недопустимая операция, нельзя перемножить)

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;
AB - 2x3 , BA - неопределена, нельзя перемножить

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8;
AB - 8x8 , BA - 3x3

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4
AB -4x4 , BA -4x4 .

2. Найдите сумму и произведение матриц  𝐴=(1 -2
3 0)  и  𝐵=(4 -1 
0 5).


In [4]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма: A + B\n{A + B}')
print(f'Произведение: AB\n{np.dot(A, B)}')

Сумма: A + B
[[ 5 -3]
 [ 3  5]]
Произведение: AB
[[  4 -11]
 [ 12  -3]]


3. _3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3*\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2*\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4*\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

B2 = -2*B

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = \n{3*A + B2 + 4*C}\n")

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = 
[[ 11  -5]
 [  9 -12]]



4. Дана матрица  𝐴=4521−23 . Вычислите  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
print(f'Матрица AA^T\n{np.dot(A, AT)}')
print(f'Матрица A^T*A\n{np.dot(AT, A)}')

Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^T*A
[[45  0]
 [ 0 14]]


5*. Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [7]:
def matrix_func(matrix_A, matrix_B):
    sum_ = 0     
    matrix_ = []    
    matrix_С = [] 
    if len(matrix_B)!=len(matrix_A[0]): 
        print("Матрицы не могут быть перемножены")       
    else:
        for z in range(0, len(matrix_A)):
            for j in range(0,len(matrix_B[0])):
                for i in range(0,len(matrix_A[0])):
                   sum_ += matrix_A[z][i]*matrix_B[i][j]
                matrix_.append(sum_)
                sum_ = 0
            matrix_С.append(matrix_)
            matrix_ = []           
    return matrix_С

In [9]:
a = np.array([[-2, 1], [0, 3]])
b = np.array([[-1, 4], [5, 0]])
matrix_func(a, b)

[[7, -8], [15, 0]]

__1.__ Вычислите определитель

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

 $$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$ = sinx sinx + cosx cosx = sin^2x +  cos^2x = 1

In [11]:
A = np.array([[4, 1], [5, -2]])
print(f'Определитель: sin^2(x)+cos^2(x) = 1')

Определитель: sin^2(x)+cos^2(x) = 1


б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$ = 4*5*9 = 180

In [20]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель: 4 * 5 * 9 = 180')
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 4 * 5 * 9 = 180
Определитель: 180


в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$$
= $1 * $$\begin{vmatrix}
5 & 6\\ 
8 & 9\\ 
\end{vmatrix}$$ -2 * $$\begin{vmatrix}
4 & 6\\ 
7 & 9\\ 
\end{vmatrix}$$ + 3 * $$\begin{vmatrix}
4 & 5\\ 
7 & 8\\ 
\end{vmatrix}$$ = -3+12-9 = 0$

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: -0


2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$ = $det(AA)$ = $|A|$*$|A|$ = 4 * 4 = 16
    
   б) $det(A^{T})$ = $det(A)$ = 4
    
   в) $det(2A)$ = $2^2 * |A|$ = 16

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю. Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю. Т.к. первая строка = (-2) умножить на вторую строку, т.е. они линейно зависимы, то определитель = 0


$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$ = $-2 * $$\begin{vmatrix}
-14 & 6\\ 
7 & 13\\ 
\end{vmatrix}$$ -7 * $$\begin{vmatrix}
4 & 6\\ 
3 & 13\\ 
\end{vmatrix}$$ - 3 * $$\begin{vmatrix}
4 & -14\\ 
3 & 7\\ 
\end{vmatrix}$$ = -2 * (-182 - 42) -7 * (52-18) -3*(28+52) = 448 - 238 - 210 = 0$

In [17]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 0


__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [18]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'{a}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}')

[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [19]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'{b}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(b)}')

[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
